### ISSUE TITLE
Update order flow to work with market price orders

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro#10]
If users create orders with market price (without sats amount) we need to change the order flow but having in mind that don't break the order flow for orders with sats amount fixed.

Case 1: Sell order published

1. buyer takes the order but the price is given by mostro
2. mostro send a DM to buyer ask an invoice for n sats amount
3. buyer use a new command sendinvoice to send the invoice to the bot, like `mostro-cli sendinvoice -o id -i lnbc1...`
4. mostro ask to seller to pay the hold invoice
the rest works like now

Case 2: Buy order published
1. seller takes the order, mostro calculates the price and send the hold invoice to be paid by seller
2. seller pays and mostro send a DM to buyer ask an invoice for n sats amount
3. buyer use a new command sendinvoice to send the invoice to the bot, like `mostro-cli sendinvoice -o id -i lnbc1...`
the rest works like now

**Comment by arkanoider** [comment]
Hi @grunch , I was thinking about a thing during the test of sell order published. Let me know what you think.

I am thinking to use just _Takesell_ command to get also marketplace order, because in the end the logic is very similar to the new _SendInvoice_ command. Let me breakdown my simple idea:

1. Seller publish sell order at market price.
2. Buyer sees the offer and Takesell it.
3. Mostro checks that offer is market price kind and sends a dm to buyer with Invoice details on amount : price calculated + premium
4. Buyer gets the message, creates the invoice on his wallet and sends again a Takesell to mostro with the correct invoice
5. Mostro shows hold invoice to seller and then we proceed as usual.

I just think this is good because the SendInvoice will do quite the the same logic of takesell with the exception of showing hold invoice to seller, so we avoid another command and some repetitive code on the CLI.

Let me know!

**Comment by grunch** [comment]
closing via PR [#9](https://github.com/MostroP2P/mostro/pull/9) and [#20](https://github.com/MostroP2P/mostro/pull/20)
