### ISSUE TITLE
Panics on trying to take a dispute from a non allowed user

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro#236]
If you try to take the dispute from an account that is not allowed, apparently mostrod received a message with action CantDo and it panics, it looks like mostrod is sending to itself a message with action CantDo.

it panics when it gets here 

https://github.com/MostroP2P/mostro/blob/main/src/app.rs#L120

**Comment by arkanoider** [comment]
Hi @grunch ,

just replicated this in this scenario:

- Created a `Sell` order --> Taksell order --> Addinvoice --> Payinvoice --> Create dispute -->  Take dispute as Admin

Loop message comes from here in `admin_take_disputes.rs` :

```Rust
 info!("Dispute {} taken by {}", dispute_id, event.pubkey);
    // We create a Message for admin
    let message = Message::new_dispute(
        Some(dispute_id),
        None,
        Action::AdminTakeDispute,
        Some(Content::Order(new_order)),
    );
    let message = message.as_json()?;
    // Send the message
    send_dm(&event.pubkey, message.clone()).await?;

```

Solutions that I propose:

- Remove the DM send when is admin taking dispute, just adding a check, but losing the dm message to Admin.
- Creating a new Action ( example AdminTookDispute or something like that ) that is discarded in the main loop as you correctly pointed out in the tg chat.

I think second one is better, because is more aligned to mostro behaviour without special cases.

I can try to arrange a new release of mostro-core with the new Action and the fix on mostrod....
Will drop pr after a test.

**Comment by arkanoider** [comment]
implemented a quick solution in #237

**Comment by grunch** [comment]
why don't we discard all messages that are not on the match? something like 

_ => ()

**Comment by arkanoider** [comment]
Look to pr...i did it with an info!() just to print what is arrived in case...

if we just discard probably we have always the loop because from what I saw Mostro is sending a Action::AdminTakeDispute message to himself triggering again the main fn..sends again and again...we should break this option with another action.

**Comment by arkanoider** [comment]
> why don't we discard all messages that are not on the match? something like
> 
> _ => ()

Probably you're thinking at the case of `CantDo` that mostrod send to himself, but try the otherscenario where mostrod send to himself admintake dispute command...

**Comment by grunch** [comment]
What if any other user start sending to Mostro Actions that are not on the match in app.rs?

**Comment by arkanoider** [comment]
Lot of `info!` printed as log at the moment. If you think that could be a bad thing to flood log I agree with you with :+1: 

_ => ()

as last match arm to silently discard all wrong actions message.

I was also looking if we can avoid the new action that I triggered when admin takes a dispute, but here we are sending this:

```Rust
 // We create a Message for admin
    let message = Message::new_dispute(
        Some(dispute_id),
        None,
        Action::AdminAcceptDispute,
        Some(Content::Order(new_order)),
    );
```

So we are yet using content field to send the order related to dispute, otherwise we could use a `TextMessage` field to avoid loop and send a message to mostro himself.

If you have better ideas @grunch let me know, open to discussion. This could be a starting point to fix potential loop issue.

**Comment by grunch** [comment]
great, I think we can leave it this way for now and see how it behaves, thanks buddy

closing it via #237
